package models.common.database;

/* Libraries */
import java.util.Date;
import javax.persistence.*;
import play.data.format.Formats;
import play.data.validation.Constraints;

/**
 * TODO: Add JavaDocs for this class.
 */
@Entity
@Table(name="users")
public class User {

    // ===========================================================
    // Global Variables
    // ===========================================================

    /** <p>Unique ID for each user.</p> */
    @Id
    @GeneratedValue
    public Long id;

    /** <p>User's Email and Login User Name</p> */
    @Constraints.Email
    public String email;

    /** <p>User's First Name</p> */
    @Constraints.Required
    public String firstName;

    /** <p>User's Last Name</p> */
    @Constraints.Required
    public String lastName;

    /** <p>User's Password (Hashed)</p> */
    @Constraints.Required
    public String password;

    /** <p>User Type</p> */
    public int userType;

    /** <p>Last Login Date</p> */
    @Formats.DateTime(pattern="yyyy-MM-dd")
    public Date lastLogin;

    /** <p>Account Creation Date</p> */
    @Formats.DateTime(pattern="yyyy-MM-dd")
    public Date createdOn;

    /** <p>User's Default Project</p> */
    public String currentProject;

    /** <p>Boolean flag to check if User
     * is authenticated or not.</p> */
    public Boolean authenticated;

    /** <p>Temporary code generated by the system
     * for authentication purposes.</p> */
    public String confirmationCode;
}